# This file is to be overwritten by nwg-displays if you choose to use it.
# nwg-displays is a graphical tool for managing monitors. 
# - Installation for Arch Linux: sudo pacman -S nwg-displays
# - Repo: https://github.com/nwg-piotr/nwg-displays

workspace = 1, monitor: eDP-1
workspace = 2, monitor: eDP-1
workspace = 3, monitor: eDP-1
workspace = 4, monitor: eDP-1
workspace = 5, monitor: eDP-1
workspace = 6, monitor: DP-1
workspace = 7, monitor: DP-1
workspace = 8, monitor: DP-1
workspace = 9, monitor: DP-1
workspace = 10, monitor: DP-1

workspace = 11, monitor: eDP-1
workspace = 12, monitor: eDP-1
workspace = 13, monitor: eDP-1
workspace = 14, monitor: eDP-1
workspace = 15, monitor: eDP-1
workspace = 16, monitor: DP-1
workspace = 17, monitor: DP-1
workspace = 18, monitor: DP-1
workspace = 19, monitor: DP-1
workspace = 20, monitor: DP-1

workspace = 21, monitor: eDP-1
workspace = 22, monitor: eDP-1
workspace = 23, monitor: eDP-1
workspace = 24, monitor: eDP-1
workspace = 25, monitor: eDP-1
workspace = 26, monitor: DP-1
workspace = 27, monitor: DP-1
workspace = 28, monitor: DP-1
workspace = 29, monitor: DP-1
workspace = 30, monitor: DP-1

workspace = 31, monitor: eDP-1
workspace = 32, monitor: eDP-1
workspace = 33, monitor: eDP-1
workspace = 34, monitor: eDP-1
workspace = 35, monitor: eDP-1
workspace = 36, monitor: DP-1
workspace = 37, monitor: DP-1
workspace = 38, monitor: DP-1
workspace = 39, monitor: DP-1
workspace = 40, monitor: DP-1

workspace = 41, monitor: eDP-1
workspace = 42, monitor: eDP-1
workspace = 43, monitor: eDP-1
workspace = 44, monitor: eDP-1
workspace = 45, monitor: eDP-1
workspace = 46, monitor: DP-1
workspace = 47, monitor: DP-1
workspace = 48, monitor: DP-1
workspace = 49, monitor: DP-1
workspace = 50, monitor: DP-1

workspace = 51, monitor: eDP-1
workspace = 52, monitor: eDP-1
workspace = 53, monitor: eDP-1
workspace = 54, monitor: eDP-1
workspace = 55, monitor: eDP-1
workspace = 56, monitor: DP-1
workspace = 57, monitor: DP-1
workspace = 58, monitor: DP-1
workspace = 59, monitor: DP-1
workspace = 60, monitor: DP-1

workspace = 61, monitor: eDP-1
workspace = 62, monitor: eDP-1
workspace = 63, monitor: eDP-1
workspace = 64, monitor: eDP-1
workspace = 65, monitor: eDP-1
workspace = 66, monitor: DP-1
workspace = 67, monitor: DP-1
workspace = 68, monitor: DP-1
workspace = 69, monitor: DP-1
workspace = 70, monitor: DP-1

workspace = 71, monitor: eDP-1
workspace = 72, monitor: eDP-1
workspace = 73, monitor: eDP-1
workspace = 74, monitor: eDP-1
workspace = 75, monitor: eDP-1
workspace = 76, monitor: DP-1
workspace = 77, monitor: DP-1
workspace = 78, monitor: DP-1
workspace = 79, monitor: DP-1
workspace = 80, monitor: DP-1

workspace = 81, monitor: eDP-1
workspace = 82, monitor: eDP-1
workspace = 83, monitor: eDP-1
workspace = 84, monitor: eDP-1
workspace = 85, monitor: eDP-1
workspace = 86, monitor: DP-1
workspace = 87, monitor: DP-1
workspace = 88, monitor: DP-1
workspace = 89, monitor: DP-1
workspace = 90, monitor: DP-1

workspace = 91, monitor: eDP-1
workspace = 92, monitor: eDP-1
workspace = 93, monitor: eDP-1
workspace = 94, monitor: eDP-1
workspace = 95, monitor: eDP-1
workspace = 96, monitor: DP-1
workspace = 97, monitor: DP-1
workspace = 98, monitor: DP-1
workspace = 99, monitor: DP-1
workspace = 100, monitor: DP-1