# Bar, wallpaper
exec-once = ~/.config/hypr/hyprland/scripts/start_geoclue_agent.sh
exec-once = swaybg -i ~/Pictures/wallpaper-selection/YoRHa/YoRHa.png -m fill
exec-once = qs -c $qsConfig &
exec-once = ~/.config/hypr/custom/scripts/__restore_video_wallpaper.sh
#exec-once = ~/.config/hypr/hyprland/scripts/wayland-blit-to-layer_overlay/mkv_overlay ~/.config/hypr/hyprland/scripts/wayland-blit-to-layer_overlay/output.mkv

# Core components (authentication, lock screen, notification daemon)
exec-once = dbus-update-activation-environment --all
exec-once = sleep 1 # Some fix idk
exec-once = gnome-keyring-daemon --start --daemonize --components=secrets

# Audio
exec-once = easyeffects --hide-window --service-mode

# Clipboard: history
# exec-once = wl-paste --watch cliphist store &
exec-once = wl-paste --type text --watch bash -c 'cliphist store && qs -c $qsConfig ipc call cliphistService update'
exec-once = wl-paste --type image --watch bash -c 'cliphist store && qs -c $qsConfig ipc call cliphistService update'

exec-once = pipewire
exec-once = pipewire-pulse
exec-once = wireplumber

# Cursor
exec-once = hyprctl setcursor Bibata-Modern-Classic 24

# Applications
exec-once = hyprctl dispatch -- exec [workspace 10 silent] kitty --session="~/.config/btop/kitty-session"
